function generateSquare(Xsw, Ysw, Xne, Yne, n)
clc;
close all
n = (n - 4) / 4;
if n ~= ceil(n)
    n = ceil(n);
    disp(['Number of nodes is rounded to ', num2str(4 * n + 4)]);
end

X = linspace(Xsw, Xne, n + 2)';
Y = linspace(Ysw, Yne, n + 2)';

coordinate = [Xsw, Ysw; ...
              X(2:end-1), Ysw * ones(n, 1); ...
              Xne, Ysw; ...
              Xne * ones(n, 1), Y(2:end-1); ...
              Xne, Yne; ...
              flipud(X(2:end-1)), Yne * ones(n, 1); ...
              Xsw, Yne; ...
              Xsw * ones(n, 1), flipud(Y(2:end-1))];

dlmwrite('pointCloud.txt', coordinate);